# -*- coding: utf-8 -*-
"""clase4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJ1X9QLyXubcu_kGsl1LGz8lRBbGErOv
"""

import pandas as pd

data = pd.read_csv("/content/credit_card.csv", on_bad_lines='skip')

data.head()

data.describe()

data.info()

data['NAME_CONTRACT_TYPE'].info()

data.isnull()

data.describe()

data.isnull().sum()

data.value_counts('NAME_CONTRACT_TYPE')

data.value_counts('CODE_GENDER')

data.value_counts('FLAG_OWN_CAR')

data.value_counts('NAME_INCOME_TYPE')

data.value_counts('FLAG_OWN_REALTY')

data.value_counts('FAMILY_STATUS')

data.value_counts('OCCUPATION_TYPE')

import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))


data['CREDIT'] = pd.to_numeric(data['CREDIT'], errors='coerce')



plt.hist(data['CREDIT'], bins=10, color='blue', rwidth=0.7, edgecolor='black')


promedio = data['CREDIT'].mean()

plt.axvline(promedio, color='red', linestyle='dashed', linewidth=2, label=f'Media: {promedio:.2f}')
plt.xticks(rotation=40)

import seaborn as sns #Importo seaborn
import matplotlib.pyplot as plt #Importo matplotlib

# 1. Configuramos el estilo de fondo
sns.set_theme(style="ticks")

# 2. Creamos el lienzo (tamaño de la imagen)
plt.figure(figsize=(12, 6))

# 3. Dibujamos el Boxplot con el truco para la línea central
sns.boxplot(
    data=data,
    x='FAM_MEMBERS',
    y='CREDIT',
    hue='FAM_MEMBERS',
    palette="viridis",
    legend=False,

    medianprops={"color": "yellow", "linewidth": 2}
)


sns.despine(offset=10, trim=True)

plt.title("Distribución de Crédito por Miembros de la Familia", fontsize=14, fontweight='bold')
plt.ylabel("Monto del Crédito")
plt.xlabel("Miembros de la Familia")


plt.ticklabel_format(style='plain', axis='y')


plt.show()