# -*- coding: utf-8 -*-
"""clase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f81KqtYLB2C9FtEWa9NSbJmR2bFJDt1w

#NUMPY INSTALACION
"""

pip install numpy

import numpy as np
a = np.array(42)

print(a)

"""import numpy as np
matrix = [1,2,3][2,3,5][3,5,6]
print(type(matrix))
print(matrix)

multiplicacion =np.array(2*3)
print(multiplicacion)
"""

multiplicacion =np.array(2*3)
print(multiplicacion)

eye_range =np.eye(7)
print(eye_range)

division =np.array(7/2)
print(division)

n = np.random.rand(5)-6
print(n)

"""#JUEGO DE DADOS"""

n = 6*np.random.rand()+1 #generar dado de 1 a 6 en un tiro
print(int(n)) #ahora el n sera entero 'int'

dado = np.random.randint(low=1, high=7)
print(dado)

n = np.random.randint(low=1, high=7, size=5)
print(n)

numero = np.random.randint(low=1, high=100)
print(numero)

"""JUEGO DE CARTAS"""

import numpy as np

pikas = [5, 0]
trebol = [9, 10]
diamante = [11, 12]
corazon = [13, 14]

a = np.array(pikas)
b = np.array(trebol)
c = np.array(diamante)
d = np.array(corazon)
print(type(a), type(b), type(c), type(d))
print(a,b,c,d)

all_cards=np.array([a,b,c,d])
print(all_cards)

"""INSTALACION DE MATPLOBIT Y USO DE GRAFICAS"""

pip install matplotlib

matrix = np.array([[2,3,4],[2,3,4],[2,4,6]])
print(matrix)

import matplotlib.pyplot as plt
plt.plot(n)
plt.show()
print(n)

import matplotlib.pyplot as plt
plt.plot(matrix)
plt.show()
print(matrix)

vector =np.array([30,40,30,40,23])
print(vector)

import matplotlib.pyplot as plt
plt.plot(vector)
plt.show()
print(vector)

edad = np.arange(0, 10)
print(edad)

base_crecimiento = edad * 6
random_variation = np.random.randn(len(edad)) * 2
crecimiento = base_crecimiento + random_variation
print(crecimiento)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(edad, crecimiento, marker='o', linestyle='-')
plt.title('Growth Over Time with Random Variation')
plt.xlabel('Edad (Years)')
plt.ylabel('Crecimiento (Units)')
plt.grid(True)
plt.show()

texto =""
print(len(texto))

import matplotlib.pyplot as plt
plt.plot(crecimiento)
plt.show()
print(crecimiento)
plt.plot(tiempo/crecimiento)
plt.show()
print(tiempo/crecimiento)

"""#PANDAS"""

pip install pandas

import pandas as pd
from pandas import Series, DataFrame

apj =pd.Series([4,7,-5,5])

print(apj)

import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], "c": [2,3,4]})
print(df)

import pandas as pd

datos_estatura = {
    "nombre": ["luis","paco","augusto"],
     "apellido": ["gonzales","rojas","lopez"],

    "edad": [23,34,2],
  "estatura": [ 1.60,1.69,187]


    }

    datos_estaturanew = estatura

df = pd.DataFrame(datos_estatura)
print(df)

"""

DATA FRAME
"""

df=pd.DataFrame(datos_estatura)

df.head()

import pandas as pd

datos_estatura = {
    "nombre": ["luis","paco","augusto"],
    "apellido": ["gonzales","rojas","lopez"],
    "edad": [23,34,2],
    "estatura": [ 1.60,1.69,187]
}

df = pd.DataFrame(datos_estatura)
print(df)

df.head ()

import pandas as pd

new_data = {
    "producto": ["Manzana", "Banana", "Naranja", "Pera", "Uva"],
    "precio": [1.5, 0.75, 1.2, 2.0, 3.5],
    "cantidad": [100, 150, 80, 50, 120]
}

new_df = pd.DataFrame(new_data)
display(new_df.head())