# -*- coding: utf-8 -*-
"""clase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143E1-j7qqXrJ2X_5DN-gx9Kz_FDGmrn3

# Introducción a Pandas
"""

# Instalación de Pandas
!pip install pandas
!pip install pyarrow

import pandas as pd

s = pd.Series([2, 4, 6, 8, 10])
print(s)

import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], "c": [2,3,4]})
print(df)

import pandas as pd

datos_estatura = {
    "nombre": ["luis","paco","augusto"],
     "apellido": ["gonzales","rojas","lopez"],

    "edad": [23,34,2],
  "estatura": [ 1.60,1.69,187]


    }

df = pd.DataFrame(datos_estatura)
print(df)

"""elementos de un objeto Series"""

s = pd.Series([2, 4, 6, 8], index=["num1", "num2", "num3", "num4"])
print(s)

s["num2"]

s.loc["num3"]

s.iloc[3]

s.iloc[2]

import numpy as np
np.sum(s)

pip install matplotlib

"""INSTALACION MATPLTLIB"""

import matplotlib.pyplot as plt
plt.plot(s)
plt.show()
print(s)

import matplotlib.pyplot as plt
plt.plot(s)
plt.show()
print(s)

personas = {
    "peso": pd.Series([84, 90, 56, 64], ["Santiago","Pedro", "Ana", "Julia"]),
    "altura": pd.Series({"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}),
    "hijos": pd.Series([2, 3], ["Pedro", "Julia"])
}

df = pd.DataFrame(personas)
df

personas = {
    "peso": pd.Series([84, 90, 56, 64], ["Santiago","Pedro", "Ana", "Julia"]),
    "altura": pd.Series({"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}),
    "hijos": pd.Series([2, 3], ["Pedro", "Julia"])
}

df = pd.DataFrame(
        personas,
        columns = ["altura", "peso"],
        index = ["Ana", "Julia", "Santiago"])
df

personas = {
    "peso": pd.Series([84, 90, 56, 64], ["Santiago","Pedro", "Ana", "Julia"]),
    "altura": pd.Series({"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}),
    "hijos": pd.Series([2, 3], ["Pedro", "Julia"])
}

df = pd.DataFrame(personas)
df

df[["peso", "altura"]]

df["peso"]

df[df["peso"] > 80]

df["peso"] > 80

"""LISTAS DEL DSATA FRAME"""

df.loc["Ana"]

df.iloc[1:3]

max_altura = 180
df.eval("altura > @max_altura")

df['media_altura'] = df['altura'] / 2.0

personas = {
    "peso": pd.Series([84, 90, 56, 64], ["Santiago","Pedro", "Ana", "Julia"]),
    "altura": pd.Series({"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}),
    "hijos": pd.Series([2, 3], ["Pedro", "Julia"])
}

df = pd.DataFrame(personas)
df

df.to_csv("df_personas.csv")
df.to_html("df_personas.html")
df.to_json("df_personas.json")