# -*- coding: utf-8 -*-
"""clase5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Nf5W-zQV9LTJc6BjptwRKN2JrfPiypw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid', palette='deep')
plt.rcParams['figure.figsize'] = (10,8)
print(' Generando datos de la empresa')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)
n = 1000

# Crear dataset
df_hr = pd.DataFrame({
    'ID_Empleado': range(1, n + 1),
    'Departamento': np.random.choice(['Ingenieria', 'Ventas', 'Marketing', 'Directivos'], n, p=[0.5, 0.3, 0.15, 0.05]),
    'Edad': np.random.normal(34, 8, n).astype(int),
    'Años_Experiencia': np.random.normal(8, 4, n).clip(0, 40).astype(int),
    'Puntaje_desempeño': np.random.normal(75, 12, n).clip(0, 100).round(1)
})

# Visualizaciones
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. Distribución por departamento
df_hr['Departamento'].value_counts().plot(kind='bar', ax=axes[0,0], color='skyblue')
axes[0,0].set_title('Empleados por Departamento')
axes[0,0].set_ylabel('Cantidad')

# 2. Distribución de edad
axes[0,1].hist(df_hr['Edad'], bins=20, color='coral', edgecolor='black')
axes[0,1].set_title('Distribución de Edad')
axes[0,1].set_xlabel('Edad')
axes[0,1].set_ylabel('Frecuencia')

# 3. Experiencia vs Desempeño
axes[1,0].scatter(df_hr['Años_Experiencia'], df_hr['Puntaje_desempeño'], alpha=0.5)
axes[1,0].set_title('Experiencia vs Desempeño')
axes[1,0].set_xlabel('Años de Experiencia')
axes[1,0].set_ylabel('Puntaje de Desempeño')

# 4. Desempeño por departamento
df_hr.boxplot(column='Puntaje_desempeño', by='Departamento', ax=axes[1,1])
axes[1,1].set_title('Desempeño por Departamento')
axes[1,1].set_xlabel('Departamento')
axes[1,1].set_ylabel('Puntaje')

plt.tight_layout()
plt.show()

# Estadísticas
print(df_hr.describe())
print("\nEmpleados por departamento:")
print(df_hr['Departamento'].value_counts())

outlier_idx = df_hr[df_hr['Departamento'] == 'Directivos'].sample(5).index #Tomemos 5 Directivos puntuales del area de departamentos
df_hr.loc[outlier_idx, 'Salario_USD'] = [1500000, 2800000, 320000, 190000, 450000] #Le metemos a esos 5 directivos esos valores extremos
df_hr['Salario_USD'] = df_hr['Salario_USD'].round(2) #Redondeamos a 2 decimales el salario
print(df_hr['Edad'])
display(df_hr.head())
#print(f'\nDataset generado con {df_hr.shape[0]}')

media_edad = df_hr['Edad'].mean()
media_salario = df_hr['Salario_USD'].mean()
print(f'La edad promedio de la empresa es: {media_edad:.1f} años')
print(f'El Salario promedio (Media es ${media_salario:,.2f} USD')

# Calcular mediana y media
mediana_salario = df_hr['Salario_USD'].median()
media_salario = df_hr['Salario_USD'].mean()

print(f'Mediana: ${mediana_salario:,.0f}')
print(f'Media: ${media_salario:,.0f}')

# Gráfico
plt.figure(figsize=(12, 6))

datos = df_hr[df_hr['Salario_USD'] < 35000]

sns.histplot(datos['Salario_USD'], bins=40, color='skyblue', kde=True,
             line_kws={'linewidth': 2, 'color': 'navy'})

plt.axvline(media_salario, color='red', linestyle='--', linewidth=2,
            label=f'Media: ${media_salario:,.0f}')
plt.axvline(mediana_salario, color='green', linestyle='-', linewidth=2,
            label=f'Mediana: ${mediana_salario:,.0f}')

plt.title('Distribución de Salarios', fontsize=14, fontweight='bold')
plt.xlabel('Salario (USD)')
plt.ylabel('Empleados')
plt.xlim(0, 20000)
plt.legend()
plt.grid(alpha=0.3)
plt.show()

from numpy.random.mtrand import random
#Generación de un Dataset multivariable complejo (1000 empleados)
np.random.seed(42) #Semilla 42 porque queremos que el generador pseudo-aleatorio se comporte de la manera adecuada.
n_empleados = 1000
df_hr = pd.DataFrame(
    {
        'ID_Empleado': range(1,n_empleados + 1), #bucle de repetición
        'Departamento': np.random.choice(['Ingenieria', 'Ventas', 'Marketing', 'Directivos'], n_empleados, p=[0.5,0.3,0.15,0.05]),
        'Edad': np.random.normal(34,8,n_empleados).astype(int),
        'Años_Experiencia': np.random.normal(8,4,n_empleados).clip(0,40).astype(int),
        'Puntaje_desempeño': np.random.normal(75,12,n_empleados).clip(0,100).round(1)
    }
)

# Agregar columna Salario_USD
df_hr['Salario_USD'] = np.random.normal(5000, 2000, 1000).clip(1000, 30000).round(0)

# Calcular mediana y media
mediana_salario = df_hr['Salario_USD'].median()
media_salario = df_hr['Salario_USD'].mean()

print(f'Mediana: ${mediana_salario:,.0f}')
print(f'Media: ${media_salario:,.0f}')

# Gráfico
plt.figure(figsize=(14, 6))

datos = df_hr[df_hr['Salario_USD'] < 35000]

sns.histplot(datos['Salario_USD'], bins=40, color='skyblue', kde=True,
             line_kws={'linewidth': 3, 'color': 'navy', 'alpha': 0.8})

plt.axvline(media_salario, color='red', linestyle='--', linewidth=4,
            label=f'Media: ${media_salario:,.0f}', alpha=0.9)
plt.axvline(mediana_salario, color='green', linestyle='-', linewidth=4,
            label=f'Mediana: ${mediana_salario:,.0f}', alpha=0.9)

plt.title('Distribución de Salarios: Media vs Mediana', fontsize=16, fontweight='bold')
plt.xlabel('Salario (USD)', fontsize=13)
plt.ylabel('Empleados', fontsize=13)
plt.xlim(0, 20000)
plt.legend(fontsize=13, loc='upper right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""medida de tencion"""

# Calcular estadísticos
Q1 = df_hr['Edad'].quantile(0.25)
mediana = df_hr['Edad'].median()
media = df_hr['Edad'].mean()
Q3 = df_hr['Edad'].quantile(0.75)
IQR = Q3 - Q1
lim_sup = Q3 + 1.5 * IQR
lim_inf = Q1 - 1.5 * IQR

print(f'Q1: {Q1:.0f} | Mediana: {mediana:.0f} | Q3: {Q3:.0f}')
print(f'Límites: [{lim_inf:.0f}, {lim_sup:.0f}]')

# Gráfico
plt.figure(figsize=(12, 5))
sns.boxplot(x=df_hr['Edad'], color='lightgreen', width=0.4)

plt.axvline(Q1, color='blue', linestyle='--', linewidth=2, label=f'Q1: {Q1:.0f}')
plt.axvline(Q3, color='red', linestyle='--', linewidth=2, label=f'Q3: {Q3:.0f}')
plt.axvline(mediana, color='orange', linestyle='-', linewidth=3, label=f'Mediana: {mediana:.0f}')
plt.axvline(media, color='gray', linestyle='--', linewidth=2, label=f'Media: {media:.0f}')
plt.axvline(lim_sup, color='purple', linestyle=':', linewidth=2, label=f'Lím Sup: {lim_sup:.0f}')
plt.axvline(lim_inf, color='purple', linestyle=':', linewidth=2, label=f'Lím Inf: {lim_inf:.0f}')

plt.title('Boxplot - Distribución de Edad', fontsize=14, fontweight='bold')
plt.xlabel('Edad (años)', fontsize=12)
plt.legend(loc='upper right', fontsize=10)
plt.grid(alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

plt.figure(figsize=(30,40))
sns.boxplot(x="Departamento", y="Edad", data=df_hr, color='lightgreen', linewidth=2)
plt.ylim((0,70))

plt.figure(figsize=(30,40))
sns.boxplot(x="Departamento", y="Salario_USD", data=df_hr, color='lightgreen', linewidth=2)
plt.ylim((0,200000))

plt.figure(figsize=(12, 6))

sns.boxplot(x="Departamento", y="Puntaje_desempeño", data=df_hr,
            palette=['lightblue', 'lightgreen', 'pink', 'purple'],
            linewidth=2)

mediana_grupo = df_hr['Puntaje_desempeño'].median()
media_grupo = df_hr['Puntaje_desempeño'].mean()

plt.axhline(mediana_grupo, linewidth=2, linestyle='--', color='red',
            label=f'Mediana: {mediana_grupo:.1f}')
plt.axhline(media_grupo, linewidth=2, linestyle='-', color='blue',
            label=f'Media: {media_grupo:.1f}')

plt.title('Desempeño por Departamento', fontsize=14, fontweight='bold')
plt.xlabel('Departamento', fontsize=12)
plt.ylabel('Puntaje de Desempeño', fontsize=12)
plt.ylim(0, 110)
plt.legend(fontsize=11)
plt.grid(alpha=0.3, axis='y')
plt.tight_layout()
plt.show()