# -*- coding: utf-8 -*-
"""clase3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKMeMkBN_B5rqk0x084EUUn5DM1LibcN

Introducción a Matplotlib
"""

# Instalación de matplotlib
!pip install matplotlib

import matplotlib
import matplotlib.pyplot as plt

plt.plot([1, 2, 5, 3, 4, 5, 1])
plt.show()

import numpy as np
x = np.linspace(3, 0, 500)
y = x**2

plt.plot(x, y)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2, 2, 500)

plt.plot(x, x**2, 'b--', label="x²")
plt.plot(x, x+1, 'g', label="x+1")
plt.legend()
plt.grid()
plt.show()

fig, ax = plt.subplots(1, 2, figsize=(14, 6))

ax[0].plot(x, y, 'r-', linewidth=3)
ax[0].set_title("Parábola", fontsize=16)
ax[0].grid(alpha=0.3)

ax[1].plot(x, y2, 'm--', linewidth=3)
ax[1].set_title("Línea recta", fontsize=16)
ax[1].grid(alpha=0.3)

plt.show()

from numpy.random import rand
x, y = rand(2, 10)
plt.scatter(x, y)
plt.show()

data = [1, 1.3, 1.5, 2, 2, 0.2, 3, 3, 3, 3]

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 8))

ax1.hist(data, bins=10, rwidth=0.8, color='skyblue', edgecolor='black')
ax1.set_title("Histograma - 10 bins")
ax1.grid(alpha=0.3)

ax2.hist(data, bins=[1, 3, 3, 2.5, 3], rwidth=0.95, color='coral', edgecolor='black')
ax2.set_xlabel("Valor", fontsize=12)
ax2.set_ylabel("Frecuencia", fontsize=12)
ax2.set_title("Histograma - bins personalizados")
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.show()

from numpy.random import rand
x, y = rand(2, 100)
x2, y2 = rand(2, 100)
plt.scatter(x, y, c='blue')
plt.scatter(x2, y2, c='green')
plt.show()

data = [2, 2.3, 2.8, 3, 3.5, 4.1, 4, 4, 5, 5.2, 5.8, 6]

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6))

# Subplot 1 - bins automáticos
ax1.hist(data, bins=8, rwidth=0.8, color='steelblue', edgecolor='black')
ax1.set_ylabel("Frecuencia")
ax1.set_title("Bins automáticos")

# Subplot 2 - bins manuales
ax2.hist(data, bins=[2, 3, 4, 5, 6], rwidth=0.95, color='tomato', edgecolor='black')
ax2.set_xlabel("Valor")
ax2.set_ylabel("Frecuencia")
ax2.set_title("Bins manuales")

plt.tight_layout()
plt.show()

import numpy as np
x = np.linspace(-2, 2, 500)
y = x**2
y2 = x + 1

fig, ax = plt.subplots(figsize=(8, 5))

ax.plot(x, y, 'b--', label="x**2")
ax.plot(x, y2, 'g', label="x+1")
ax.legend(loc="best")

fig.savefig("mi_grafica.png", transparent=True)
plt.show()