# -*- coding: utf-8 -*-
"""parcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyL4yiljhDwwhvgeDuSezVba4AwmMTx5
"""

import numpy as np
import pandas as pd

np.random.seed(42)
n = 1000

# --- Parámetros basados en los datos del examen ---
niveles = ['Bachiller', 'Técnico', 'Profesional', 'Maestría', 'Doctorado']
pesos = [0.30, 0.15, 0.35, 0.15, 0.05]

salario_base = {
    'Bachiller': 1800,
    'Técnico': 2200,
    'Profesional': 2600,
    'Maestría': 3500,
    'Doctorado': 5000
}

credito_prob = {
    'Bachiller': 0.40,
    'Técnico': 0.55,
    'Profesional': 0.65,
    'Maestría': 0.75,
    'Doctorado': 0.85
}

# --- Generar columnas ---
nivel_edu = np.random.choice(niveles, size=n, p=pesos)

edades = np.clip(
    np.random.normal(32, 8, n).astype(int), 18, 65
)

salarios = np.array([
    max(800, np.random.normal(salario_base[nv], salario_base[nv] * 0.25))
    for nv in nivel_edu
])

# ~3% de outliers (como el Cliente 5 del examen con $45,000)
outlier_idx = np.random.choice(n, size=int(n * 0.03), replace=False)
salarios[outlier_idx] *= np.random.uniform(8, 20, len(outlier_idx))

credito = np.array([
    'Sí' if np.random.random() < credito_prob[nv] else 'No'
    for nv in nivel_edu
])

# --- Crear DataFrame ---
df = pd.DataFrame({
    'ID_Cliente': range(1, n + 1),
    'Edad': edades,
    'Salario_Mensual': salarios.round(2),
    'Nivel_Educativo': nivel_edu,
    'Credito_Aprobado': credito
})

# --- Mostrar resultados ---
print(f"✅ Dataset generado: {n} registros\n")
print(df.head(10).to_string(index=False))
print(f"\n... ({n - 10} filas más)\n")

print("=" * 45)
print(" RESUMEN ESTADÍSTICO")
print("=" * 45)
print(df.describe())

print("\n Distribución Nivel Educativo:")
print(df['Nivel_Educativo'].value_counts())

print("\n Crédito Aprobado:")
print(df['Credito_Aprobado'].value_counts())

# --- Guardar CSV (opcional) ---
df.to_csv('clientes_sinteticos.csv', index=False)
print("\n💾 Guardado como: clientes_sinteticos.csv")

import matplotlib.pyplot as plt

"""HISTOGRAMA"""

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Distribución de variables numéricas — Clientes sintéticos', fontsize=14, y=1.02)

# --- Histograma: Salario Mensual ---
ax1 = axes[0]
ax1.hist(df['Salario_Mensual'], bins=50, color='#378ADD', edgecolor='white', linewidth=0.4)
ax1.set_title('Salario mensual')
ax1.set_xlabel('Salario ($)')
ax1.set_ylabel('Frecuencia')
ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x:,.0f}'))
ax1.tick_params(axis='x', rotation=30)

# --- Histograma: Edad ---
ax2 = axes[1]
ax2.hist(df['Edad'], bins=30, color='#1D9E75', edgecolor='white', linewidth=0.4)
ax2.set_title('Edad')
ax2.set_xlabel('Edad (años)')
ax2.set_ylabel('Frecuencia')

# --- Histograma: Salario sin outliers (zoom) ---
q99 = df['Salario_Mensual'].quantile(0.99)
df_sin_outliers = df[df['Salario_Mensual'] <= q99]

ax3 = axes[2]
ax3.hist(df_sin_outliers['Salario_Mensual'], bins=40, color='#7F77DD', edgecolor='white', linewidth=0.4)
ax3.set_title('Salario mensual (sin top 1% outliers)')
ax3.set_xlabel('Salario ($)')
ax3.set_ylabel('Frecuencia')
ax3.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x:,.0f}'))
ax3.tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.savefig('histogramas_clientes.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n📊 Outliers removidos en zoom: {n - len(df_sin_outliers)} registros (top 1%)")
print(f"   Salario máx sin outliers: ${q99:,.2f}")
print(f"   Salario máx con outliers: ${df['Salario_Mensual'].max():,.2f}")

"""#1. Salario mensual (con outliers)
La distribución está fuertemente sesgada a la derecha.
La mayoría de los clientes gana menos de $5,000–$6,000.
Hay algunos valores extremadamente altos (outliers) que llegan hasta ≈ $60,964, lo que estira la gráfica.
Esto indica que existen pocos clientes con ingresos muy altos que distorsionan la distribución general.
#. Edad
La distribución es más equilibrada (casi normal).
La mayoría de las edades se concentra entre 25 y 40 años.
Hay menos clientes en los extremos (menores de 20 o mayores de 50).
Esto sugiere una base de clientes principalmente en edad laboral activa.
#. Salario mensual
Al eliminar los valores extremos, la distribución se vuelve más clara y concentrada.
#El salario máximo baja a aproximadamente $35,159.
Se observa mejor que la mayoría gana entre $1,000 y $6,000, con una cola derecha más corta.
Esto permite analizar el comportamiento típico sin la distorsión de ingresos muy altos.
Conclusión general
Los salarios presentan alta desigualdad (asimetría positiva) debido a pocos ingresos muy altos.
La edad está bien distribuida, sin valores extremos problemáticos.
Quitar outliers ayuda a entender mejor el patrón real de la mayoría de los clientes.
"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

orden = ['Bachiller', 'Técnico', 'Profesional', 'Maestría', 'Doctorado']
datos = [df[df['Nivel_Educativo'] == nv]['Salario_Mensual'].values for nv in orden]

axes[0].boxplot(datos, labels=orden, patch_artist=True)
axes[0].set_title('Salario por nivel educativo')
axes[0].tick_params(axis='x', rotation=15)

datos_edad = [df[df['Credito_Aprobado'] == v]['Edad'].values for v in ['Sí', 'No']]
axes[1].boxplot(datos_edad, labels=['Crédito: Sí', 'Crédito: No'], patch_artist=True)
axes[1].set_title('Edad por crédito aprobado')

plt.tight_layout()
plt.show()

"""1. Salario por nivel educativo
Se observa una tendencia creciente clara: a mayor nivel educativo, mayor salario.
Las medianas (línea dentro de cada caja) suben progresivamente.
También aumenta la dispersión en niveles educativos altos: hay más variabilidad en salarios.
Existen muchos outliers altos (puntos individuales), especialmente en niveles educativos superiores, lo que indica que algunas personas ganan muchísimo más que el promedio.

👉 Interpretación:

La educación está positivamente correlacionada con el ingreso.
Sin embargo, en niveles altos hay más desigualdad salarial (algunos ganan mucho más que otros con la misma educación).
2. Edad por crédito aprobado
Las distribuciones de edad para “aprobado” y “no aprobado” son muy similares.
Las medianas están casi en el mismo rango (alrededor de 30–33 años).
Los rangos (cajas y bigotes) también son bastante parecidos.
Hay algunos outliers en edades más altas, pero en ambos grupos.

👉 Interpretación:

La edad no parece ser un factor determinante fuerte para la aprobación del crédito.
Probablemente otras variables (como ingreso, historial crediticio, etc.) tienen mayor peso.
Conclusión general
Educación → influye fuertemente en el salario.
Edad → no muestra impacto claro en la aprobación del crédito
"""

from numpy.random import rand
import matplotlib.pyplot as plt

x,  y  = rand(2, 100)
x2, y2 = rand(2, 100)

plt.scatter(x,  y,  c='blue')
plt.scatter(x2, y2, c='green')
plt.show()

"""🔍 ¿Qué se observa?
Los puntos están distribuidos de forma bastante uniforme en todo el espacio.
Los colores (clases) están muy mezclados entre sí.
No se aprecian fronteras claras ni separaciones naturales entre los grupos.
No hay patrones visibles como líneas, curvas o agrupaciones definidas.
📊 Interpretación
Las variables representadas en los ejes (aunque no están etiquetadas aquí) no discriminan bien entre las clases.
Es decir, con solo estas dos variables:
Es difícil predecir si un punto será azul o verde.
Esto sugiere que:
No hay correlación fuerte entre estas variables y la variable objetivo (clase).
Un modelo simple (como regresión logística lineal) tendría bajo rendimiento usando solo estas características.
"""