# -*- coding: utf-8 -*-
"""trabajocustomers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D24Vl_RMtdEw8PjWCOQnAlaoEa6aiVK7

EXPLICACION DEL CODIGO PASO A PASO


*import pandas as pd
*employee_df = pd.read_csv("customers_1 (1).csv")
*Lee el archivo CSV y lo guarda en una variable llamada employee_df que es un DataFrame, como una tabla
"""

tabla = pd.DataFrame({
    'Variable': employee_df.columns,
    'Tipo de dato': employee_df.dtypes.astype(str).replace({
        'int64': 'Número entero',
        'float64': 'Número decimal',
        'object': 'Texto'
    }),
    'Escala de medición': ['Nominal', 'Razón', 'Ordinal', 'Razón', 'Nominal', 'Nominal', 'Nominal', 'Ordinal']
})

tabla.style.set_table_styles([
    {'selector': 'th', 'props': [('background-color', '#3C3489'), ('color', 'white'), ('font-size', '13pt')]},
]).set_properties(**{
    'background-color': '#f0f8ff',
    'color': 'black',
    'border-color': '#cccccc',
    'font-size': '12pt'
}).hide(axis='index')

"""### 📊 Explicación de la Gráfica: Mediana y Moda de Ingresos por Género

Esta gráfica presenta dos medidas de tendencia central (mediana y moda) para los ingresos, desglosadas por género, para ayudarnos a entender la distribución salarial.

-   **Barras Azules (Mediana de Ingresos)**:
    La altura de las barras azules representa la **mediana** de los ingresos para cada género. La mediana es el valor central en un conjunto de datos ordenado, lo que significa que el 50% de las personas gana menos que este valor y el otro 50% gana más. Es una medida útil porque es menos sensible a valores extremos (ingresos muy altos o muy bajos) que el promedio.
    -   **Mediana para Hombres**: Aproximadamente **$122,352.5**
    -   **Mediana para Mujeres**: Aproximadamente **$108,666**
    
    *Interpretación*: Los hombres en este conjunto de datos tienen una mediana de ingresos más alta que las mujeres, lo que sugiere que, en general, la mitad de los hombres ganan más que la mitad de las mujeres.

-   **Marcadores 'X' Rojos (Moda de Ingresos)**:
    Los marcadores 'X' rojos indican la **moda** de los ingresos para cada género. La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. En el contexto de ingresos, es el ingreso más común o frecuente.
    -   **Moda para Hombres**: Aproximadamente **$83,687**
    -   **Moda para Mujeres**: Aproximadamente **$102,543**

    *Interpretación*: Sorprendentemente, el ingreso más frecuente entre las mujeres es más alto que el ingreso más frecuente entre los hombres. Esto contrasta con la mediana y sugiere que, aunque la mitad de los hombres ganen más que la mitad de las mujeres, el salario que más se repite para las mujeres es mayor.

**Conclusión General**:
Esta gráfica nos muestra que las distribuciones de ingresos pueden ser complejas. Mientras que la **mediana** indica que los hombres tienden a tener ingresos más altos en el punto medio, la **moda** revela que el ingreso individual más frecuente es mayor para las mujeres. Esto podría deberse a diferentes concentraciones de personas en ciertos rangos salariales dentro de cada grupo de género, lo que sugiere que los patrones de ingresos no son uniformes y pueden tener múltiples picos o asimetrías.
"""

from IPython.display import display, HTML

display(HTML("<h3 style='font-family:sans-serif; color:#3C3489;'>📊 Mediana y Moda de Ingresos por Género</h3>"))

tabla_stats = employee_df.groupby('Gender')['Income'].agg(
    Mediana='median',
    Moda=lambda x: x.mode()[0]
).reset_index()

display(tabla_stats.style.set_table_styles([
    {'selector': 'th', 'props': [('background-color', '#3C3489'), ('color', 'white'), ('font-size', '13pt')]}
]).set_properties(**{
    'background-color': '#f0f8ff',
    'color': 'black',
    'border-color': '#cccccc',
    'font-size': '12pt'
}).hide(axis='index').format({
    'Mediana': '${:,.0f}',
    'Moda': '${:,.0f}'
}))

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
sns.set_theme(style="whitegrid")

# Replace 'Male' and 'Female' with 'Hombres' and 'Mujeres' for better understanding
employee_df['Gender'] = employee_df['Gender'].replace({'Male': 'Hombres', 'Female': 'Mujeres'})

median_income = employee_df.groupby('Gender')['Income'].median().reset_index()

mode_income = employee_df.groupby('Gender')['Income'].apply(lambda x: x.mode()[0] if not x.mode().empty else None).reset_index(name='Mode_Income')

f, ax = plt.subplots(figsize=(8, 6))

sns.barplot(data=median_income, x='Gender', y='Income', palette='vlag', ax=ax, alpha=0.7, label='Mediana')


combined_stats = median_income.set_index('Gender').join(mode_income.set_index('Gender'))

sns.scatterplot(data=combined_stats.reset_index(), x='Gender', y='Mode_Income', color='red', marker='X', s=200, zorder=5, label='Moda')

plt.title("Mediana y Moda de Ingresos por Género")
plt.xlabel("Hombres / Mujeres")
plt.ylabel("Ingresos")
plt.legend(title='Estadística')
plt.tight_layout()
plt.show()

"""Moda:

Las mujeres tienen una moda más alta ($102,543) que los hombres ($83,687), lo que significa que el ingreso más frecuente en mujeres es mayor.
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
sns.set_theme(style="whitegrid")


employee_df = pd.read_csv("customers_1 (1).csv")




f, ax = plt.subplots(figsize=(10, 6))


sns.violinplot(data=employee_df, x="Gender", y="Income", palette="vlag", inner=None)


median_income = employee_df.groupby('Gender')['Income'].median().reset_index()
mode_income = employee_df.groupby('Gender')['Income'].apply(lambda x: x.mode()[0] if not x.mode().empty else None).reset_index(name='Mode_Income')


sns.scatterplot(data=median_income, x='Gender', y='Income', color='blue', marker='o', s=150, zorder=5, label='Mediana')


sns.scatterplot(data=mode_income, x='Gender', y='Mode_Income', color='red', marker='X', s=200, zorder=5, label='Moda')


plt.title("Distribución de Ingresos por Género con Mediana y Moda")
plt.xlabel("Género")
plt.ylabel("Ingresos")
plt.legend(title='Estadística')
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

employee_df.median(numeric_only=True)

employee_df.mode().iloc[0]

import seaborn as sns
sns.boxplot(x="Gender", y="Income", data=employee_df)

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="whitegrid")

plt.figure(figsize=(8, 6))


employee_df['Gender'] = employee_df['Gender'].replace({'Male': 'Hombres', 'Female': 'Mujeres'})

sns.boxplot(x="Gender", y="Income",
            data=employee_df,
            palette=["#3C3489", "#ADD8E6"])

plt.title("Distribución de Ingresos por Género", fontsize=16, color="#3C3489")
plt.xlabel("Género", fontsize=13)
plt.ylabel("Ingresos", fontsize=13)
sns.despine(offset=10, trim=True)
plt.tight_layout()
plt.show()

"""Conclusión:
Los hombres tienden a ganar más pero con más variabilidad. Las mujeres tienen ingresos más concentrados y consistentes.

---
INGRESO MAS ALTO
"""

employee_df.nlargest(10, 'Income')

sns.violinplot(x="Ocupacion", y="Income", hue="Gender", data=employee_df.nlargest(10, 'Income'))

sns.barplot(x="CustomerID", y="Income", hue="Gender", data=employee_df.nlargest(10, 'Income'))

employee_df.groupby('Gender')['Income'].mean()

sns.barplot(x="Gender", y="Income", data=employee_df, palette=["#3C3489", "#ADD8E6"])

hombres = employee_df[employee_df['Gender'] == 'Hombres']['Income'].mean()
mujeres = employee_df[employee_df['Gender'] == 'Mujeres']['Income'].mean()

diferencia = ((hombres - mujeres) / hombres) * 100

print(f"Los hombres ganan {diferencia:.2f}% más que las mujeres")